/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    measurements: Measurement;
    workouts: Workout;
    routines: Routine;
    'food-entries': FoodEntry;
    stickers: Sticker;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    measurements: MeasurementsSelect<false> | MeasurementsSelect<true>;
    workouts: WorkoutsSelect<false> | WorkoutsSelect<true>;
    routines: RoutinesSelect<false> | RoutinesSelect<true>;
    'food-entries': FoodEntriesSelect<false> | FoodEntriesSelect<true>;
    stickers: StickersSelect<false> | StickersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'member' | 'admin';
  profile?: {
    age?: number | null;
    heightIn?: number | null;
    calorieFormula?: ('m' | 'f') | null;
    goals?: ('glutes' | 'tone' | 'bulk' | 'strong' | 'lose' | 'stamina')[] | null;
    trainingDays?: number | null;
    sessionMinutes?: number | null;
    experience?: ('beg' | 'int' | 'adv') | null;
    location?: ('home' | 'gym') | null;
    equipment?: string[] | null;
    goEasyOn?: ('back' | 'shoulder' | 'knee')[] | null;
    measurementTargets?:
      | {
          measure: 'weight' | 'waist' | 'hips' | 'chest' | 'arm' | 'thigh' | 'bf';
          value: number;
          id?: string | null;
        }[]
      | null;
    liftTargets?:
      | {
          lift: 'bench' | 'squat' | 'deadlift' | 'ohp' | 'thrust';
          oneRepMaxLb: number;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "measurements".
 */
export interface Measurement {
  id: number;
  owner: number | User;
  date: string;
  weight?: number | null;
  waist?: number | null;
  hips?: number | null;
  chest?: number | null;
  arm?: number | null;
  thigh?: number | null;
  bodyFat?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workouts".
 */
export interface Workout {
  id: number;
  owner: number | User;
  date: string;
  title: string;
  exercises?:
    | {
        name: string;
        repLow?: number | null;
        repHigh?: number | null;
        targetRpe?: number | null;
        sets?:
          | {
              weight?: number | null;
              reps?: number | null;
              rpe?: number | null;
              done?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "routines".
 */
export interface Routine {
  id: number;
  owner: number | User;
  title: string;
  days?:
    | {
        label: string;
        type?: ('full' | 'upper' | 'lower' | 'push' | 'pull' | 'legs') | null;
        items?:
          | {
              exercise: string;
              pattern?: string | null;
              sets?: number | null;
              reps?: string | null;
              restSeconds?: number | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "food-entries".
 */
export interface FoodEntry {
  id: number;
  owner: number | User;
  date: string;
  meal: 'Breakfast' | 'Lunch' | 'Dinner' | 'Snack';
  food: string;
  kcal: number;
  protein?: number | null;
  carbs?: number | null;
  fat?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stickers".
 */
export interface Sticker {
  id: number;
  owner: number | User;
  tab: 'me' | 'log' | 'routine' | 'food' | 'progress' | 'library';
  kind: string;
  x: number;
  y: number;
  rotation?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'measurements';
        value: number | Measurement;
      } | null)
    | ({
        relationTo: 'workouts';
        value: number | Workout;
      } | null)
    | ({
        relationTo: 'routines';
        value: number | Routine;
      } | null)
    | ({
        relationTo: 'food-entries';
        value: number | FoodEntry;
      } | null)
    | ({
        relationTo: 'stickers';
        value: number | Sticker;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  profile?:
    | T
    | {
        age?: T;
        heightIn?: T;
        calorieFormula?: T;
        goals?: T;
        trainingDays?: T;
        sessionMinutes?: T;
        experience?: T;
        location?: T;
        equipment?: T;
        goEasyOn?: T;
        measurementTargets?:
          | T
          | {
              measure?: T;
              value?: T;
              id?: T;
            };
        liftTargets?:
          | T
          | {
              lift?: T;
              oneRepMaxLb?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "measurements_select".
 */
export interface MeasurementsSelect<T extends boolean = true> {
  owner?: T;
  date?: T;
  weight?: T;
  waist?: T;
  hips?: T;
  chest?: T;
  arm?: T;
  thigh?: T;
  bodyFat?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workouts_select".
 */
export interface WorkoutsSelect<T extends boolean = true> {
  owner?: T;
  date?: T;
  title?: T;
  exercises?:
    | T
    | {
        name?: T;
        repLow?: T;
        repHigh?: T;
        targetRpe?: T;
        sets?:
          | T
          | {
              weight?: T;
              reps?: T;
              rpe?: T;
              done?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "routines_select".
 */
export interface RoutinesSelect<T extends boolean = true> {
  owner?: T;
  title?: T;
  days?:
    | T
    | {
        label?: T;
        type?: T;
        items?:
          | T
          | {
              exercise?: T;
              pattern?: T;
              sets?: T;
              reps?: T;
              restSeconds?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "food-entries_select".
 */
export interface FoodEntriesSelect<T extends boolean = true> {
  owner?: T;
  date?: T;
  meal?: T;
  food?: T;
  kcal?: T;
  protein?: T;
  carbs?: T;
  fat?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stickers_select".
 */
export interface StickersSelect<T extends boolean = true> {
  owner?: T;
  tab?: T;
  kind?: T;
  x?: T;
  y?: T;
  rotation?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}